version: "3"

services: 
    animeflv:
        build: "."
        image: apiad/animeflv-downloader
        volumes: 
            - ".:/src"
        command: ["python3", "-m", "animeflv.bot", "${TOKEN}"]
