version: "3"

services: 
    animeflv:
        build: "."
        container_name: animeflv-bot
        image: ed0/animeflv-downloader
        command: ["python3", "-m", "animeflv.bot", "${TOKEN}"]
        restart: unless-stopped
        volumes:
          - ./output:/src/output #Optional
          #- ./config:/root/.megaCmd #Optional
          #- ./data:/root/MEGA #Optional
